const API_BASE_URL = "http://localhost:5000";
const NANOSECONDS = 1;
const MICROSECONDS = 1000 * NANOSECONDS;
const MILLISECONDS = 1000 * MICROSECONDS;

const SECONDS_JS = 1;
const MILLISECONDS_JS = 1000 * SECONDS_JS;

export {API_BASE_URL, MILLISECONDS, MILLISECONDS_JS};